export const lorem = [`
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et malesuada fames ac turpis egestas sed. Bibendum neque egestas congue quisque egestas diam in. Fermentum et sollicitudin ac orci. Sit amet consectetur adipiscing elit ut. Ipsum consequat nisl vel pretium lectus. Malesuada fames ac turpis egestas maecenas pharetra convallis. Mattis nunc sed blandit libero volutpat sed cras ornare. Tincidunt id aliquet risus feugiat in ante. Consequat interdum varius sit amet mattis. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Morbi blandit cursus risus at ultrices mi. Ut lectus arcu bibendum at. Magna fringilla urna porttitor rhoncus dolor purus. Nulla porttitor massa id neque aliquam vestibulum morbi. Urna nunc id cursus metus aliquam. Purus in mollis nunc sed id semper. Consectetur lorem donec massa sapien faucibus. Eget mauris pharetra et ultrices neque ornare aenean euismod elementum.

Varius duis at consectetur lorem donec massa sapien. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Scelerisque purus semper eget duis. Neque aliquam vestibulum morbi blandit cursus risus. Vel quam elementum pulvinar etiam non quam. Diam donec adipiscing tristique risus nec feugiat. Semper quis lectus nulla at volutpat diam ut. Ac turpis egestas maecenas pharetra convallis posuere. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Porta lorem mollis aliquam ut. Magna ac placerat vestibulum lectus mauris ultrices eros. In arcu cursus euismod quis viverra. Ut tristique et egestas quis.

Aliquam faucibus purus in massa tempor nec. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Eu scelerisque felis imperdiet proin fermentum leo vel orci. Dictum non consectetur a erat nam at lectus urna duis. Arcu cursus euismod quis viverra. Interdum posuere lorem ipsum dolor. Diam vulputate ut pharetra sit amet aliquam id. Enim blandit volutpat maecenas volutpat blandit aliquam. Nulla malesuada pellentesque elit eget gravida cum sociis natoque 

Aliquam faucibus purus in massa tempor nec. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Eu scelerisque felis imperdiet proin fermentum leo vel orci. Dictum non consectetur a erat nam at lectus urna duis. Arcu cursus euismod quis viverra. Interdum posuere lorem ipsum dolor. Diam vulputate ut pharetra sit amet aliquam id. Enim blandit volutpat maecenas volutpat blandit aliquam. Nulla malesuada pellentesque elit eget gravida cum sociis natoque 
`]

export const lorem1 = [`
Mi eget mauris pharetra et. Eget dolor morbi non arcu risus quis varius quam quisque. Suspendisse sed nisi lacus sed viverra tellus in hac. Mi sit amet mauris commodo quis imperdiet massa tincidunt. Nulla facilisi nullam vehicula ipsum a arcu. Quis commodo odio aenean sed adipiscing diam donec adipiscing. Scelerisque eu ultrices vitae auctor eu augue ut. Elit pellentesque habitant morbi tristique senectus et netus et. Morbi tincidunt ornare massa eget egestas purus viverra accumsan. Feugiat in fermentum posuere urna nec tincidunt praesent. Venenatis urna cursus eget nunc. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Aliquet lectus proin nibh nisl. Risus in hendrerit gravida rutrum quisque non tellus orci. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi etiam.

Pretium viverra suspendisse potenti nullam ac tortor vitae. Ut diam quam nulla porttitor massa id neque aliquam. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Dolor magna eget est lorem ipsum dolor sit. Duis ultricies lacus sed turpis tincidunt id aliquet. Dapibus ultrices in iaculis nunc. Amet nisl purus in mollis nunc sed id semper. Mi ipsum faucibus vitae aliquet. Bibendum neque egestas congue quisque egestas diam in arcu cursus. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Risus feugiat in ante metus dictum at tempor commodo. Non enim praesent elementum facilisis leo vel. Netus et malesuada fames ac turpis.

Ut consequat semper viverra nam. Turpis massa sed elementum tempus egestas sed sed risus pretium. Pharetra et ultrices neque ornare aenean euismod elementum nisi quis. Ullamcorper sit amet risus nullam. Elit pellentesque habitant morbi tristique senectus. Facilisi morbi tempus iaculis urna id. Nibh tortor id aliquet lectus proin nibh. Condimentum lacinia quis vel eros donec ac odio tempor. In hac habitasse platea dictumst quisque. Condimentum lacinia quis vel eros donec ac. Cursus turpis massa tincidunt dui. Vitae congue eu consequat ac felis donec et odio. Eget sit amet tellus cras adipiscing enim eu turpis egestas. Eget nunc scelerisque viverra mauris in aliquam sem fringilla. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Sociis natoque penatibus et magnis dis parturient montes nascetur. Elementum nibh tellus molestie nunc non.

`]

export const lorem2 = [`

Eget nunc scelerisque viverra mauris in. Sed blandit libero volutpat sed cras ornare arcu. Arcu felis bibendum ut tristique. At elementum eu facilisis sed odio morbi quis commodo odio. Urna porttitor rhoncus dolor purus non enim. Et magnis dis parturient montes nascetur ridiculus mus mauris vitae. Porttitor massa id neque aliquam vestibulum. A arcu cursus vitae congue mauris rhoncus. Sodales ut eu sem integer vitae justo eget magna fermentum. Proin fermentum leo vel orci porta non. Egestas erat imperdiet sed euismod nisi porta lorem mollis. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Elit eget gravida cum sociis natoque penatibus et. Arcu cursus vitae congue mauris.

Amet volutpat consequat mauris nunc congue nisi vitae suscipit tellus. Sit amet justo donec enim diam vulputate ut pharetra. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Quis imperdiet massa tincidunt nunc. Ac odio tempor orci dapibus ultrices in iaculis. Quis vel eros donec ac odio tempor orci. Sit amet consectetur adipiscing elit ut. Netus et malesuada fames ac turpis egestas. Malesuada pellentesque elit eget gravida cum sociis natoque. Sed risus pretium quam vulputate dignissim suspendisse. Aliquam sem et tortor consequat id porta. Sem fringilla ut morbi tincidunt augue. Quisque non tellus orci ac. Magna sit amet purus gravida quis blandit turpis cursus in. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Donec enim diam vulputate ut pharetra sit amet aliquam. Lacus luctus accumsan tortor posuere.

Non blandit massa enim nec dui nunc. Posuere ac ut consequat semper viverra nam. Netus et malesuada fames ac turpis. Eros in cursus turpis massa tincidunt dui. Hendrerit gravida rutrum quisque non tellus orci ac. Aenean euismod elementum nisi quis eleifend quam. Vestibulum lectus mauris ultrices eros in. Lectus mauris ultrices eros in cursus turpis massa. Purus ut faucibus pulvinar elementum integer enim neque volutpat ac. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Fermentum dui faucibus in ornare. Id consectetur purus ut faucibus. Nibh tortor id aliquet lectus proin nibh nisl. Vulputate dignissim suspendisse in est ante in nibh mauris. Amet venenatis urna cursus eget nunc scelerisque viverra mauris in. Eget aliquet nibh praesent tristique magna sit amet purus. Egestas dui id ornare arcu odio ut sem. Morbi blandit cursus risus at ultrices. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in.
`]

export const lorem3 = [` 
Risus feugiat in ante metus dictum. Pulvinar etiam non quam lacus suspendisse. Dolor sed viverra ipsum nunc. Amet consectetur adipiscing elit pellentesque habitant. Blandit massa enim nec dui nunc mattis enim. Non odio euismod lacinia at. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Nam aliquam sem et tortor consequat id porta nibh. Ipsum faucibus vitae aliquet nec ullamcorper sit amet. Volutpat commodo sed egestas egestas fringilla phasellus. Mauris ultrices eros in cursus. Odio pellentesque diam volutpat commodo sed egestas. Eget magna fermentum iaculis eu non. Neque volutpat ac tincidunt vitae semper.

Dictum at tempor commodo ullamcorper a lacus vestibulum sed. Nullam non nisi est sit amet. Eget nulla facilisi etiam dignissim diam quis. Quam id leo in vitae turpis massa. Duis convallis convallis tellus id. Tristique senectus et netus et malesuada fames ac turpis egestas. In fermentum posuere urna nec tincidunt. Nulla facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Turpis cursus in hac habitasse platea dictumst quisque. Imperdiet proin fermentum leo vel orci porta. Iaculis at erat pellentesque adipiscing. Sit amet nulla facilisi morbi. Aliquam etiam erat velit scelerisque in. Cras fermentum odio eu feugiat pretium nibh. Consectetur libero id faucibus nisl tincidunt eget. Turpis egestas sed tempus urna et. Purus in massa tempor nec feugiat. Nullam non nisi est sit amet facilisis magna. Netus et malesuada fames ac turpis.

Pharetra massa massa ultricies mi quis hendrerit dolor magna eget. Amet luctus venenatis lectus magna fringilla urna porttitor. Montes nascetur ridiculus mus mauris vitae ultricies leo. Quam elementum pulvinar etiam non quam lacus. Sed id semper risus in hendrerit gravida. Purus in mollis nunc sed id semper risus in hendrerit. Massa tempor nec feugiat nisl pretium. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Pulvinar etiam non quam lacus suspendisse faucibus interdum. Tellus pellentesque eu tincidunt tortor aliquam. Pellentesque dignissim enim sit amet venenatis. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Sit amet facilisis magna etiam tempor orci eu lobortis elementum. Ac tortor vitae purus faucibus ornare suspendisse. Et leo duis ut diam quam nulla porttitor massa id. Orci eu lobortis elementum nibh tellus molestie nunc. Nunc eget lorem dolor sed. Metus vulputate eu scelerisque felis. Ornare arcu dui vivamus arcu felis.

Aliquam faucibus purus in massa tempor nec. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Eu scelerisque felis imperdiet proin fermentum leo vel orci. Dictum non consectetur a erat nam at lectus urna duis. Arcu cursus euismod quis viverra. Interdum posuere lorem ipsum dolor. Diam vulputate ut pharetra sit amet aliquam id. Enim blandit volutpat maecenas volutpat blandit aliquam. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Iaculis urna id volutpat lacus laoreet non. Diam sollicitudin tempor id eu nisl nunc mi ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada. Tortor id aliquet lectus proin nibh nisl. Odio pellentesque diam volutpat commodo sed egestas egestas. Quam viverra orci sagittis eu volutpat odio facilisis. Praesent tristique magna sit amet purus gravida quis blandit turpis. Lobortis scelerisque fermentum dui faucibus in ornare quam. Purus in massa tempor nec. Nibh sed pulvinar proin gravida hendrerit.

Senectus et netus et malesuada fames ac turpis egestas. Scelerisque in dictum non consectetur a erat. Donec massa sapien faucibus et molestie ac feugiat sed. Sem et tortor consequat id porta nibh. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna. Et magnis dis parturient montes nascetur. Urna et pharetra pharetra massa massa ultricies mi. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Placerat duis ultricies lacus sed turpis tincidunt id. Tincidunt eget nullam non nisi est sit amet. Dictumst quisque sagittis purus sit amet volutpat. Sed libero enim sed faucibus turpis in eu. Magna fermentum iaculis eu non diam phasellus vestibulum. Sed felis eget velit aliquet sagittis id consectetur. Lorem sed risus ultricies tristique nulla.

Lectus mauris ultrices eros in. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Eget duis at tellus at. Non odio euismod lacinia at quis risus. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Sed blandit libero volutpat sed cras ornare arcu dui vivamus. Tristique senectus et netus et malesuada fames ac. Cursus risus at ultrices mi tempus imperdiet. Hac habitasse platea dictumst quisque sagittis purus.

Ultrices dui sapien eget mi proin sed libero enim. Tellus in metus vulputate eu. Mi proin sed libero enim. Aliquam ultrices sagittis orci a scelerisque. Nullam non nisi est sit amet facilisis magna. Vestibulum lectus mauris ultrices eros in cursus. Elit scelerisque mauris pellentesque pulvinar. Massa massa ultricies mi quis hendrerit dolor magna. Sed vulputate odio ut enim blandit volutpat. Eget arcu dictum varius duis at consectetur. Sed pulvinar proin gravida hendrerit. Praesent semper feugiat nibh sed pulvinar proin. Et pharetra pharetra massa massa ultricies mi. Habitant morbi tristique senectus et netus et. Vitae nunc sed velit dignissim. Feugiat in fermentum posuere urna nec tincidunt praesent semper feugiat.
`]